apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: padel-dev

labels:
  - pairs:
      environment: development
      project: padel-reservation-system
