services:

  config-server:
    build: ./config-server
    container_name: config-server
    image: ${DOCKERHUB_USERNAME}/config-server:latest
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/app/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/app/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - padel-network

  eureka-server:
    build: ./eureka-server
    image: ${DOCKERHUB_USERNAME}/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - padel-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - padel-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - padel-network


  user-service:
    build: ./user-service
    image: ${DOCKERHUB_USERNAME}/user-service:latest
    container_name: user-service
    ports:
      - "8770:8770"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
      - PREFER_IP=true
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - padel-network

  club-service:
    build: ./club-service
    image: ${DOCKERHUB_USERNAME}/club-service:latest
    container_name: club-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=club-service
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
      - PREFER_IP=true
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - padel-network

  reservation-service:
    build: ./reservation-service
    image: ${DOCKERHUB_USERNAME}/reservation-service:latest
    container_name: reservation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=reservation-service
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
      - PREFER_IP=true
    depends_on:
        config-server:
          condition: service_healthy
        eureka-server:
          condition: service_healthy
        postgres:
          condition: service_started
        rabbitmq:
          condition: service_started
    networks:
      - padel-network

  review-service:
    build: ./review-service
    image: ${DOCKERHUB_USERNAME}/review-service:latest
    container_name: review-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=review-service
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
      - PREFER_IP=true
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - padel-network

  notification-service:
    build: ./notification-service
    image: ${DOCKERHUB_USERNAME}/notification-service:latest
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
      - PREFER_IP=true
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - padel-network

  api-gateway:
    build: ./api-gateway
    image: ${DOCKERHUB_USERNAME}/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - CONFIG_SERVER_URL=http://config-server:8888/
      - EUREKA_HOST=eureka-server
      - PREFER_IP=true
    depends_on:
      - eureka-server
      - user-service
    networks:
      - padel-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - padel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - padel-network

volumes:
  postgres-data:

networks:
  padel-network:
    driver: bridge