apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-service
  template:
    metadata:
      labels:
        app: club-service
    spec:
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: ['sh', '-c', 'until wget -q -O - http://config-server:8888/actuator/health; do echo waiting for config-server; sleep 2; done']
      containers:
        - name: club-service
          image: milospejic001/club-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/club_db
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
                      httpGet:
                        path: /actuator/health
                        port: 8081
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      failureThreshold: 5