apiVersion: v1
kind: ConfigMap
metadata: 
  name: postgres-init-script
data:
  create-databases.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE club_db;
    CREATE DATABASE reservation_db;
    CREATE DATABASE review_db;
    CREATE DATABASE notification_db;