apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: padel-prod

labels:
  - pairs:
      environment: production
      project: padel-reservation-system
